# Generated by Django 4.0.4 on 2022-09-29 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentCausation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_factor', models.CharField(blank=True, max_length=250)),
                ('accident_subfactor', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollisionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collision_type', models.CharField(blank=True, max_length=250)),
                ('collision_subtype', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrashType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash_type', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Clear Night'), (2, 'Cloudy'), (3, 'Day'), (4, 'Fog'), (5, 'Hail'), (6, 'Partially cloudy day'), (7, 'Partially cloudy night'), (8, 'Rain'), (9, 'Rain'), (10, 'Wind')], null=True)),
                ('light', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Dawn'), (2, 'Day'), (3, 'Dusk'), (4, 'Night')], null=True)),
                ('severity', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Damage to Property'), (2, 'Fatal'), (3, 'Non-Fatal')], null=True)),
                ('movement_code', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accident_factor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='incidentreport.accidentcausation')),
                ('collision_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='incidentreport.collisiontype')),
                ('crash_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='incidentreport.crashtype')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=250)),
                ('incident_upload_photovideo', models.ImageField(default='user.jpeg', upload_to='incident_report/image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('upload_photovideo', models.ImageField(default='user.jpeg', upload_to='incident_report/image')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Diplomat'), (2, 'Government'), (3, 'Private'), (4, 'Public / For Hire`')], null=True)),
                ('vehicle_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ambulance'), (2, 'Animal'), (3, 'Armored Car'), (4, 'Bicycle'), (5, 'Bus'), (6, 'Car'), (7, 'Electric Bike'), (8, 'Habal-habal '), (9, 'Heavy Equipment'), (10, 'Horse-Driven Carriage (Tartanilla)'), (11, 'Jeepney'), (12, 'Motorcycle'), (13, 'Pedestrian'), (14, 'Pedicab'), (15, 'Push-Cart'), (16, 'SUV'), (17, 'Taxi (metered)'), (18, 'Tricycle (Articulated)'), (19, 'Truck (Fire)'), (20, 'Truck (Pick-up)'), (21, 'Truck (Rigid)'), (22, 'Truck (Unknown)'), (23, 'Van'), (24, 'Water Vessel'), (25, 'Others')], null=True)),
                ('brand', models.CharField(blank=True, max_length=250)),
                ('plate_number', models.CharField(blank=True, max_length=250)),
                ('engine_number', models.CharField(blank=True, max_length=250)),
                ('chassis_number', models.CharField(blank=True, max_length=250)),
                ('insurance_details', models.TextField(blank=True, max_length=250)),
                ('maneuver', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Left-turn'), (2, 'Right-turn'), (3, 'U-turn'), (4, 'Cross Traffic'), (5, 'Merging'), (6, 'Diverging'), (7, 'Overtaking'), (8, 'Going Ahead'), (9, 'Reversing'), (10, 'Sudden Start'), (11, 'Sudden Stop'), (12, 'Parked Off Road'), (13, 'Parked On Road')], null=True)),
                ('damage', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'None'), (2, 'Front'), (3, 'Left'), (4, 'Multiple'), (5, 'Rear'), (6, 'Right'), (7, 'Roof')], null=True)),
                ('defect', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'None'), (2, 'Breaks'), (3, 'Lights'), (4, 'Multiple'), (5, 'Steering'), (6, 'Tires')], null=True)),
                ('loading', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Legal'), (2, 'Overloaded'), (3, 'Unsafe Load'), (4, 'Others')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_general', models.ManyToManyField(blank=True, null=True, to='incidentreport.incidentgeneral')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder', models.CharField(blank=True, max_length=250)),
                ('action_taken', models.TextField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_general', models.ManyToManyField(blank=True, null=True, to='incidentreport.incidentgeneral')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_first_name', models.CharField(blank=True, max_length=250)),
                ('incident_middle_name', models.CharField(blank=True, max_length=250)),
                ('incident_last_name', models.CharField(blank=True, max_length=250)),
                ('incident_age', models.CharField(blank=True, max_length=250)),
                ('incident_gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Female'), (2, 'Male')], null=True)),
                ('incident_address', models.CharField(blank=True, max_length=250)),
                ('incident_involvement', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pedestrian'), (2, 'Witness'), (3, 'Passenger'), (4, 'Driver')], null=True)),
                ('incident_id_presented', models.PositiveSmallIntegerField(blank=True, choices=[(1, "Driver's License"), (2, 'Government'), (3, 'Passport'), (4, 'School Id'), (5, 'Others')], null=True)),
                ('incident_id_number', models.CharField(blank=True, max_length=250)),
                ('incident_injury', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Fatal'), (2, 'Minor'), (3, 'Not Injured'), (4, 'Serious')], null=True)),
                ('incident_driver_error', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Bad Overtaking'), (2, 'Bad Turning'), (3, 'Fatigued / Asleep'), (4, 'Inattentive'), (5, 'No Signal'), (6, 'Too Close'), (7, 'Too Fast'), (8, 'Using Cellphone')], null=True)),
                ('incident_alcohol_drugs', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Alcohol Suspected'), (2, 'Drugs suspected')], null=True)),
                ('incident_seatbelt_helmet', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Seat belt/Helmet Worn'), (2, 'Not worn'), (3, 'Not worn correctly')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_general', models.ManyToManyField(blank=True, null=True, to='incidentreport.incidentgeneral')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userreport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidentreport.userreport')),
            ],
        ),
    ]
