# Generated by Django 4.1.2 on 2022-11-15 13:03

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import incidentreport.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentCausation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('category', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollisionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('category', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrashType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('crash_type', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('generalid', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=6, null=True)),
                ('latitude', models.FloatField(blank=True, max_length=20, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=20, null=True)),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('upload_photovideo', models.FileField(blank=True, null=True, upload_to=incidentreport.models.incident_image_upload_path)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], null=True)),
                ('duplicate', models.CharField(blank=True, choices=[('Duplicate', 'Duplicate'), ('Possible Duplicate', 'Possible Duplicate'), ('Not Duplicate', 'Not Duplicate')], max_length=250, null=True)),
                ('weather', models.CharField(blank=True, choices=[('Clear Night', 'Clear Night'), ('Cloudy', 'Cloudy'), ('Day', 'Day'), ('Fog', 'Fog'), ('Hail', 'Hail'), ('Partially cloudy day', 'Partially cloudy day'), ('Partially cloudy night', 'Partially cloudy night'), ('Rain', 'Rain'), ('Rain', 'Rain'), ('Wind', 'Wind')], max_length=250, null=True)),
                ('light', models.CharField(blank=True, choices=[('Dawn', 'Dawn'), ('Day', 'Day'), ('Dusk', 'Dusk'), ('Night', 'Night')], max_length=250, null=True)),
                ('severity', models.CharField(blank=True, choices=[('Damage to Property', 'Damage to Property'), ('Fatal', 'Fatal'), ('Non-Fatal', 'Non-Fatal')], max_length=250, null=True)),
                ('movement_code', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accident_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidentreport.accidentcausation')),
                ('collision_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidentreport.collisiontype')),
                ('crash_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidentreport.crashtype')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('classification', models.CharField(blank=True, choices=[('Diplomat', 'Diplomat'), ('Government', 'Government'), ('Private', 'Private'), ('Public / For Hire`', 'Public / For Hire`')], max_length=250, null=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('Ambulance', 'Ambulance'), ('Animal', 'Animal'), ('Armored Car', 'Armored Car'), ('Bicycle', 'Bicycle'), ('Bus', 'Bus'), ('Car', 'Car'), ('Electric Bike', 'Electric Bike'), ('Habal-habal', 'Habal-habal'), ('Heavy Equipment', 'Heavy Equipment'), ('Horse-Driven Carriage (Tartanilla)', 'Horse-Driven Carriage (Tartanilla)'), ('Jeepney', 'Jeepney'), ('Motorcycle', 'Motorcycle'), ('Pedestrian', 'Pedestrian'), ('Pedicab', 'Pedicab'), ('Push-Cart', 'Push-Cart'), ('SUV', 'SUV'), ('Taxi (metered)', 'Taxi (metered)'), ('Tricycle (Articulated)', 'Tricycle (Articulated)'), ('Truck (Fire)', 'Truck (Fire)'), ('Truck (Pick-up)', 'Truck (Pick-up)'), ('Truck (Rigid)', 'Truck (Rigid)'), ('Truck (Unknown)', 'Truck (Unknown)'), ('Van', 'Van'), ('Water Vessel', 'Water Vessel'), ('Others', 'Others')], max_length=250, null=True)),
                ('brand', models.CharField(blank=True, max_length=250)),
                ('plate_number', models.CharField(blank=True, max_length=250)),
                ('engine_number', models.CharField(blank=True, max_length=250)),
                ('chassis_number', models.CharField(blank=True, max_length=250)),
                ('insurance_details', models.TextField(blank=True, max_length=250)),
                ('maneuver', models.CharField(blank=True, choices=[('Left-turn', 'Left-turn'), ('Right-turn', 'Right-turn'), ('U-turn', 'U-turn'), ('Cross Traffic', 'Cross Traffic'), ('Merging', 'Merging'), ('Diverging', 'Diverging'), ('Overtaking', 'Overtaking'), ('Going Ahead', 'Going Ahead'), ('Reversing', 'Reversing'), ('Sudden Start', 'Sudden Start'), ('Sudden Stop', 'Sudden Stop'), ('Parked Off Road', 'Parked Off Road'), ('Parked On Road', 'Parked On Road')], max_length=250, null=True)),
                ('damage', models.CharField(blank=True, choices=[('None', 'None'), ('Front', 'Front'), ('Left', 'Left'), ('Multiple', 'Multiple'), ('Rear', 'Rear'), ('Right', 'Right'), ('Roof', 'Roof')], max_length=250, null=True)),
                ('defect', models.CharField(blank=True, choices=[('None', 'None'), ('Breaks', 'Breaks'), ('Lights', 'Lights'), ('Multiple', 'Multiple'), ('Steering', 'Steering'), ('Tires', 'Tires')], max_length=250, null=True)),
                ('loading', models.CharField(blank=True, choices=[('Legal', 'Legal'), ('Overloaded', 'Overloaded'), ('Unsafe Load', 'Unsafe Load'), ('Others', 'Others')], max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidentreport.incidentgeneral')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('responder', models.CharField(blank=True, max_length=250)),
                ('action_taken', models.TextField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_general', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidentreport.incidentgeneral')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('incident_first_name', models.CharField(blank=True, max_length=250)),
                ('incident_middle_name', models.CharField(blank=True, max_length=250)),
                ('incident_last_name', models.CharField(blank=True, max_length=250)),
                ('incident_age', models.CharField(blank=True, max_length=250)),
                ('incident_gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=250, null=True)),
                ('incident_address', models.CharField(blank=True, max_length=250)),
                ('incident_involvement', models.CharField(blank=True, choices=[('Pedestrian', 'Pedestrian'), ('Witness', 'Witness'), ('Passenger', 'Passenger'), ('Driver', 'Driver')], max_length=250, null=True)),
                ('incident_id_presented', models.CharField(blank=True, choices=[("Driver's License", "Driver's License"), ('Government', 'Government'), ('Passport', 'Passport'), ('School Id', 'School Id'), ('Others', 'Others')], max_length=250, null=True)),
                ('incident_id_number', models.CharField(blank=True, max_length=250)),
                ('incident_injury', models.CharField(blank=True, choices=[('Fatal', 'Fatal'), ('Minor', 'Minor'), ('Not Injured', 'Not Injured'), ('Serious', 'Serious')], max_length=250, null=True)),
                ('incident_driver_error', models.CharField(blank=True, choices=[('Bad Overtaking', 'Bad Overtaking'), ('Bad Turning', 'Bad Turning'), ('Fatigued / Asleep', 'Fatigued / Asleep'), ('Inattentive', 'Inattentive'), ('No Signal', 'No Signal'), ('Too Close', 'Too Close'), ('Too Fast', 'Too Fast'), ('Using Cellphone', 'Using Cellphone')], max_length=250, null=True)),
                ('incident_alcohol_drugs', models.CharField(blank=True, choices=[('Alcohol Suspected', 'Alcohol Suspected'), ('Drugs suspected', 'Drugs suspected')], max_length=250, null=True)),
                ('incident_seatbelt_helmet', models.CharField(blank=True, choices=[('Seat belt/Helmet Worn', 'Seat belt/Helmet Worn'), ('Not worn', 'Not worn'), ('Not worn correctly', 'Not worn correctly')], max_length=250, null=True)),
                ('incident_photo_id', models.FileField(blank=True, null=True, upload_to=incidentreport.models.path_and_rename)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidentreport.incidentgeneral')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentNotif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_general_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_general', to='incidentreport.incidentgeneral')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sender', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('media_description', models.TextField(blank=True, max_length=250)),
                ('incident_upload_photovideo', models.FileField(blank=True, null=True, upload_to=incidentreport.models.path_and_rename)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidentreport.incidentgeneral')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('incident_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidentreport.incidentgeneral')),
                ('incident_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidentreport.incidentmedia')),
                ('incident_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidentreport.incidentperson')),
                ('incident_remark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidentreport.incidentremark')),
                ('incident_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidentreport.incidentvehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
