# Generated by Django 4.1.2 on 2022-11-08 08:19

from django.db import migrations, models
import incidentreport.models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentgeneral',
            name='upload_photovideo',
            field=models.FileField(blank=True, null=True, upload_to=incidentreport.models.user_directory_path_incimage),
        ),
    ]
