# Generated by Django 4.0.4 on 2022-10-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='upload_photovideo',
            field=models.ImageField(blank=True, null=True, upload_to='incident_report/image'),
        ),
    ]
