# Generated by Django 4.1.2 on 2022-11-15 13:19

from django.db import migrations, models
import incidentreport.models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentmedia',
            name='incident_upload_photovideo',
            field=models.FileField(blank=True, null=True, upload_to=incidentreport.models.incident_image_upload_path),
        ),
        migrations.AlterField(
            model_name='incidentperson',
            name='incident_photo_id',
            field=models.FileField(blank=True, null=True, upload_to=incidentreport.models.incident_image_upload_path),
        ),
    ]
