# Generated by Django 4.0.4 on 2022-09-26 12:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidentreport', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncidentReport',
            new_name='UserReport',
        ),
    ]
