# Generated by Django 4.1.2 on 2022-10-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='userid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
