# Generated by Django 4.0.4 on 2022-10-04 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentgeneral',
            name='user_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='incidentreport.userreport'),
        ),
    ]
