# Generated by Django 4.0.4 on 2022-10-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
