# Generated by Django 4.1.2 on 2022-10-26 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0002_alter_userreport_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentgeneral',
            name='user_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidentreport.userreport'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='userid',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
