# Generated by Django 4.0.4 on 2022-10-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0002_alter_incidentgeneral_user_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentmedia',
            old_name='description',
            new_name='media_description',
        ),
    ]
