# Generated by Django 4.0.4 on 2022-10-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0002_userreport_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentgeneral',
            name='light',
            field=models.CharField(blank=True, choices=[('Dawn', 'Dawn'), ('Day', 'Day'), ('Dusk', 'Dusk'), ('Night', 'Night')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='incidentgeneral',
            name='severity',
            field=models.CharField(blank=True, choices=[('Damage to Property', 'Damage to Property'), ('Fatal', 'Fatal'), ('Non-Fatal', 'Non-Fatal')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='incidentgeneral',
            name='weather',
            field=models.CharField(blank=True, choices=[('Clear Night', 'Clear Night'), ('Cloudy', 'Cloudy'), ('Day', 'Day'), ('Fog', 'Fog'), ('Hail', 'Hail'), ('Partially cloudy day', 'Partially cloudy day'), ('Partially cloudy night', 'Partially cloudy night'), ('Rain', 'Rain'), ('Rain', 'Rain'), ('Wind', 'Wind')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='incidentperson',
            name='incident_alcohol_drugs',
            field=models.CharField(blank=True, choices=[('Alcohol Suspected', 'Alcohol Suspected'), ('Drugs suspected', 'Drugs suspected')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='incidentperson',
            name='incident_driver_error',
            field=models.CharField(blank=True, choices=[('Bad Overtaking', 'Bad Overtaking'), ('Bad Turning', 'Bad Turning'), ('Fatigued / Asleep', 'Fatigued / Asleep'), ('Inattentive', 'Inattentive'), ('No Signal', 'No Signal'), ('Too Close', 'Too Close'), ('Too Fast', 'Too Fast'), ('Using Cellphone', 'Using Cellphone')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='incidentperson',
            name='incident_gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='incidentperson',
            name='incident_id_presented',
            field=models.CharField(blank=True, choices=[("Driver's License", "Driver's License"), ('Government', 'Government'), ('Passport', 'Passport'), ('School Id', 'School Id'), ('Others', 'Others')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='incidentperson',
            name='incident_injury',
            field=models.CharField(blank=True, choices=[('Fatal', 'Fatal'), ('Minor', 'Minor'), ('Not Injured', 'Not Injured'), ('Serious', 'Serious')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='incidentperson',
            name='incident_involvement',
            field=models.CharField(blank=True, choices=[('Pedestrian', 'Pedestrian'), ('Witness', 'Witness'), ('Passenger', 'Passenger'), ('Driver', 'Driver')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='incidentperson',
            name='incident_seatbelt_helmet',
            field=models.CharField(blank=True, choices=[('Seat belt/Helmet Worn', 'Seat belt/Helmet Worn'), ('Not worn', 'Not worn'), ('Not worn correctly', 'Not worn correctly')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='incidentvehicle',
            name='classification',
            field=models.CharField(blank=True, choices=[('Diplomat', 'Diplomat'), ('Government', 'Government'), ('Private', 'Private'), ('Public / For Hire`', 'Public / For Hire`')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='incidentvehicle',
            name='damage',
            field=models.CharField(blank=True, choices=[(1, 'None'), (2, 'Front'), (3, 'Left'), (4, 'Multiple'), (5, 'Rear'), (6, 'Right'), (7, 'Roof')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='incidentvehicle',
            name='defect',
            field=models.CharField(blank=True, choices=[(1, 'None'), (2, 'Breaks'), (3, 'Lights'), (4, 'Multiple'), (5, 'Steering'), (6, 'Tires')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='incidentvehicle',
            name='loading',
            field=models.CharField(blank=True, choices=[(1, 'Legal'), (2, 'Overloaded'), (3, 'Unsafe Load'), (4, 'Others')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='incidentvehicle',
            name='maneuver',
            field=models.CharField(blank=True, choices=[('Left-turn', 'Left-turn'), ('Right-turn', 'Right-turn'), ('U-turn', 'U-turn'), ('Cross Traffic', 'Cross Traffic'), ('Merging', 'Merging'), ('Diverging', 'Diverging'), ('Overtaking', 'Overtaking'), ('Going Ahead', 'Going Ahead'), ('Reversing', 'Reversing'), ('Sudden Start', 'Sudden Start'), ('Sudden Stop', 'Sudden Stop'), ('Parked Off Road', 'Parked Off Road'), ('Parked On Road', 'Parked On Road')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='incidentvehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Ambulance', 'Ambulance'), ('Animal', 'Animal'), ('Armored Car', 'Armored Car'), ('Bicycle', 'Bicycle'), ('Bus', 'Bus'), ('Car', 'Car'), ('Electric Bike', 'Electric Bike'), ('Habal-habal', 'Habal-habal'), ('Heavy Equipment', 'Heavy Equipment'), ('Horse-Driven Carriage (Tartanilla)', 'Horse-Driven Carriage (Tartanilla)'), ('Jeepney', 'Jeepney'), ('Motorcycle', 'Motorcycle'), ('Pedestrian', 'Pedestrian'), ('Pedicab', 'Pedicab'), ('Push-Cart', 'Push-Cart'), ('SUV', 'SUV'), ('Taxi (metered)', 'Taxi (metered)'), ('Tricycle (Articulated)', 'Tricycle (Articulated)'), ('Truck (Fire)', 'Truck (Fire)'), ('Truck (Pick-up)', 'Truck (Pick-up)'), ('Truck (Rigid)', 'Truck (Rigid)'), ('Truck (Unknown)', 'Truck (Unknown)'), ('Van', 'Van'), ('Water Vessel', 'Water Vessel'), ('Others', 'Others')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='state',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
