# Generated by Django 4.0.4 on 2022-09-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0002_rename_incidentreport_userreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='upload_photo',
            field=models.ImageField(default='user.jpeg', upload_to='incident_report/image'),
        ),
    ]
