# Generated by Django 4.0.4 on 2022-09-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0003_userreport_upload_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreport',
            old_name='upload_photo',
            new_name='upload_photovideo',
        ),
    ]
