# Generated by Django 4.0.4 on 2022-09-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='user.jpeg', upload_to='users/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='upload_id',
            field=models.ImageField(default='user.jpeg', upload_to='member/id'),
        ),
    ]
