# Generated by Django 4.1.2 on 2022-11-15 13:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.user_image_upload_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='upload_id',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.user_image_upload_path),
        ),
    ]
