# Generated by Django 4.0.4 on 2022-09-30 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='Some String', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(db_index=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must not consist of space and requires country code. eg : +639171234567', regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Active'), (2, 'Deleted'), (3, 'Deactivated')], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='user.jpeg', upload_to='users/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='upload_id',
            field=models.ImageField(default='user.jpeg', upload_to='member/id'),
        ),
    ]
