# Generated by Django 4.1.2 on 2022-11-08 08:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='upload_id',
            field=models.ImageField(upload_to=accounts.models.user_directory_path_id),
        ),
    ]
